# DotNetTools build definition

trigger:
  branches:
      include:
      - master
  paths:
    include:
    - DotNetTools

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

pool:
  name: Herakles-1
  demands:
  - msbuild
  - visualstudio
  - vstest

resources:
  repositories:
    - repository: templates
      type: git
      name: \!BuildTemplates
      ref: refs/tags/v1.1

steps:
- template: appframedotnet-package.yml@templates
  parameters:
    solution: 'DotNetTools/DotNetTools.sln'
    nugetConfigPath: 'DotNetTools/NuGet.Config'
    packageProjectDirectory: 'DotNetTools/DotNetTools'

# Dokumentation bauen und in Verzeichnis hinterlegen
- task: chrismason.vsts-docfxtasks.docfx-extension-build-task.DocFxTask@0
  displayName: 'Create DocFx Documentation'
  inputs:
    solution: '_Dokumentation/docfx.json'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: 'DotNetTools/DotNetTools/bin/Debug/netstandard2.0/_Dokumentation/docs'
    Contents: '**/*.*'
    TargetFolder: '$(build.artifactstagingdirectory)/Dokumentation'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'